name: ost_env
channels:
  - menpo
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2021.5.30=py36h06a4308_0
  - cudatoolkit=10.0.130=h8c5a6a4_10
  - cudnn=7.6.5.32=ha8d7eb6_1
  - libedit=3.1.20210910=h7f8727e_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - python=3.6.9=h265db76_0
  - readline=7.0=h7b6447c_5
  - setuptools=58.0.4=py36h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.12=h5eee18b_3
  - pip:
    - absl-py==1.2.0
    - astor==0.8.1
    - backcall==0.2.0
    - cached-property==1.5.2
    - cloudpickle==2.2.0
    - dataclasses==0.8
    - decorator==5.1.1
    - gast==0.5.3
    - google-pasta==0.2.0
    - grpcio==1.48.2
    - gym==0.26.1
    - gym-notices==0.0.8
    - h5py==3.1.0
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - ipython==7.16.3
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.3.7
    - msgpack==1.0.4
    - msgpack-numpy==0.4.8
    - nibabel==3.2.2
    - numpy==1.19.5
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==1.1.5
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - pip==21.3.1
    - prompt-toolkit==3.0.31
    - protobuf==3.19.6
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - pyglet==1.5.27
    - pygments==2.13.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pyzmq==24.0.1
    - rl-medical==0.1.0
    - simpleitk==2.1.1.2
    - six==1.16.0
    - tabulate==0.8.10
    - tensorboard==1.14.0
    - tensorflow-estimator==1.14.0
    - tensorflow-gpu==1.14.0
    - tensorpack==0.9.5
    - termcolor==1.1.0
    - tqdm==4.64.1
    - traitlets==4.3.3
    - typing-extensions==4.1.1
    - wcwidth==0.2.5
    - werkzeug==2.0.3
    - wrapt==1.14.1
    - zipp==3.6.0
prefix: /homedtic/msaiz/anaconda3/envs/ost_env
